version: 1.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\Scripts\\pip.exe install --upgrade pip"
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements.txt --no-warn-script-location"

build_script:
  - mkdir build
  - cd build
  - "%PYTHON%\\Scripts\\pyinstaller.exe ../GitG.py"

test_script:
  - cd dist/GitG
  - dir
  - "GitG.exe --version"
