version: 1.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "64"

init:
  - "ECHO Python: %PYTHON% Python Version: %PYTHON_VERSION% Python Arch: x%PYTHON_ARCH%"

install:
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements.txt --no-warn-script-location"

build_script:
  - mkdir build
  - cd build
  - "%PYTHON%\\Scripts\\pyinstaller.exe --onefile --distpath ./GitG/dist --workpath ./GitG/build ../GitG.py"
  - "%PYTHON%\\Scripts\\pyinstaller.exe --onefile --distpath ./GitGSave/dist --workpath ./GitGSave/build ../GitGSave.py"

test_script:
  - cd GitG/dist
  - dir
  - "GitG.exe --version"
  - cd ../../GitGSave/dist
  - "GitGSave.exe --version"
