version: '{build}'

build:
  parallel: true
  verbosity: minimal

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "32"
      platfrom: "x86"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "64"
      platform: "x64"

init:
  - "ECHO Python-Path: %PYTHON% Python-Version: %PYTHON_VERSION% Python-Arch: x%PYTHON_ARCH%"

install:
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements.txt --no-warn-script-location"

build_script:
  - mkdir build
  - cd build
  - "%PYTHON%\\Scripts\\pyinstaller.exe --onefile --distpath ./GitG/dist --workpath ./GitG/build ../GitG.py"
  - "%PYTHON%\\Scripts\\pyinstaller.exe --onefile --distpath ./GitGSave/dist --workpath ./GitGSave/build ../GitGSave.py"

test_script:
  - cd GitG/dist
  - "xcopy ..\\..\\..\\src\\* .\\src /e /i"
  - "GitG.exe --version"
  - cd ../../GitGSave/dist
  - "xcopy ..\\..\\..\\src\\* .\\src /e /i"
  - "GitGSave.exe --version"
  - cd ../../..

artifacts:
- path: ./build/GitG/dist
  name: GitG-Win-%platform%

- path: ./build/GitGSave/dist
  name: GitGSave-Win-%platform%
