version: '{build}'

build:
  parallel: true
  verbosity: minimal

image:
  - Visual Studio 2019
  - Ubuntu

stack: python 3.8

environment:
  matrix:
    - PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "32"
      platform: "x86"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.6"
      PYTHON_ARCH: "64"
      platform: "x64"

init:
  - cmd: "echo Python-Path: %PYTHON% Python-Version: %PYTHON_VERSION% Python-Arch: x%PYTHON_ARCH%"

install:
  - cmd: "pip install -r requirements.txt --no-warn-script-location"
  - sh: "pip install -r requirements.txt --no-warn-script-location"

build_script:
  - mkdir build
  - cd build
  - cmd: "%PYTHON%\\Scripts\\pyinstaller.exe --onefile --distpath ./GitG/dist --workpath ./GitG/build ../GitG.py"
  - cmd: "%PYTHON%\\Scripts\\pyinstaller.exe --onefile --distpath ./GitGSave/dist --workpath ./GitGSave/build ../GitGSave.py"
  - sh: "pyinstaller --onefile --distpath ./GitG/dist --workpath ./GitG/build ../GitG.py"
  - sh: "pyinstaller --onefile --distpath ./GitGSave/dist --workpath ./GitGSave/build ../GitGSave.py"

test_script:
  - cd GitG/dist
  - cmd: "xcopy ..\\..\\..\\src\\* .\\src /e /i"
  - sh: "cp ../../../src/* ./src"
  - cmd: "GitG.exe --version"
  - sh: "./GitG --version"
  - cd ../../GitGSave/dist
  - cmd: "xcopy ..\\..\\..\\src\\* .\\src /e /i"
  - sh: "cp ../../../src/* ./src"
  - cmd: "GitGSave.exe --version"
  - sh: "./GitGSave --version"
  - cd ../../..

artifacts:
- path: ./build/GitG/dist
  name: GitG-$(APPVEYOR_BUILD_WORKER_IMAGE)-$(platform)

- path: ./build/GitGSave/dist
  name: GitGSave-$(APPVEYOR_BUILD_WORKER_IMAGE)-$(platform)

